### ISSUE TITLE
Animated Model Bug - Editor Panel

### ISSUE THREAD

**Issue by silferysky** [edrickhong/Cu#2]
Animated models (goblins) will occasionally distort when editor panel is opened.
![ezgif com-crop](https://user-images.githubusercontent.com/35890492/36337530-4ff6a1ba-13d3-11e8-970f-33c6f20adb1e.gif)

**Comment by edrickhong** [comment]
@silferysky Next time include the following as well: 
CPU
GPU
driver version
OS

This should be an Nvidia specific bug though I am not sure. Not sure what is causing this rn. Probably something to do w the data flushing

**Comment by edrickhong** [comment]
Looks like a thread sync issue (we perform the flush before the animation blending finishes)

**Comment by edrickhong** [comment]
Narrowed down the cause of the bug. TAlloc call is returning memory that is already allocated. Will investigate tonight.

**Comment by edrickhong** [comment]
Problem caused by the fact we write to the staging write buffer before waiting for animation blending to complete.
